const cardset = [
  { id: 1, color: "#FF0000", flipped: false, matched: false },
  { id: 2, color: "#00FF00", flipped: false, matched: false },
  { id: 3, color: "#0000FF", flipped: false, matched: false },
  { id: 4, color: "#00FFFF", flipped: false, matched: false },
  { id: 5, color: "#FF00FF", flipped: false, matched: false },
  { id: 6, color: "#FFFF00", flipped: false, matched: false },
  { id: 7, color: "#FFA500", flipped: false, matched: false },
  { id: 8, color: "#800080", flipped: false, matched: false },
  { id: 9, color: "#FFC0CB", flipped: false, matched: false },
  { id: 10, color: "#A52A2A", flipped: false, matched: false },
  { id: 11, color: "#008080", flipped: false, matched: false },
  { id: 12, color: "#00FF00", flipped: false, matched: false },
  { id: 13, color: "#4B0082", flipped: false, matched: false },
  { id: 14, color: "#800000", flipped: false, matched: false },
  { id: 15, color: "#000080", flipped: false, matched: false },
  { id: 16, color: "#808000", flipped: false, matched: false },
  { id: 17, color: "#C0C0C0", flipped: false, matched: false },
  { id: 18, color: "#FFD700", flipped: false, matched: false },
  { id: 19, color: "#FF0000", flipped: false, matched: false },
  { id: 20, color: "#00FF00", flipped: false, matched: false },
  { id: 21, color: "#0000FF", flipped: false, matched: false },
  { id: 22, color: "#00FFFF", flipped: false, matched: false },
  { id: 23, color: "#FF00FF", flipped: false, matched: false },
  { id: 24, color: "#FFFF00", flipped: false, matched: false },
  { id: 25, color: "#FFA500", flipped: false, matched: false },
  { id: 26, color: "#800080", flipped: false, matched: false },
  { id: 27, color: "#FFC0CB", flipped: false, matched: false },
  { id: 28, color: "#A52A2A", flipped: false, matched: false },
  { id: 29, color: "#008080", flipped: false, matched: false },
  { id: 30, color: "#00FF00", flipped: false, matched: false },
  { id: 31, color: "#4B0082", flipped: false, matched: false },
  { id: 32, color: "#800000", flipped: false, matched: false },
  { id: 33, color: "#000080", flipped: false, matched: false },
  { id: 34, color: "#808000", flipped: false, matched: false },
  { id: 35, color: "#C0C0C0", flipped: false, matched: false },
  { id: 36, color: "#FFD700", flipped: false, matched: false },
];

export default cardset;